lcgcmt_installarea=with_installarea
CMTPATH=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt:/hepustc/home/hengli/testarea/RPCPerf:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e
CMT_tag=$(tag)
CMTROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/CMT/v1r25p20160527
CMT_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/CMT/v1r25p20160527
CMTVERSION=v1r25p20160527
CMT_offset=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/share/bin:/hepustc/home/hengli/testarea/RPCPerf/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/InstallArea/share/bin:/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/scripts:/hepustc/home/hengli/testarea/RPCPerf/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/InstallArea/scripts:/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/${CMTCONFIG}/bin:/hepustc/home/hengli/testarea/RPCPerf/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/InstallArea/${CMTCONFIG}/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/ROOT/6.04.16/x86_64-slc6-gcc49-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/xrootd/4.2.3/x86_64-slc6-gcc49-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/gccxml/0.9.0_20131026/x86_64-slc6-gcc49-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/tcmalloc/2.4/x86_64-slc6-gcc49-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AtlasSite/gcc-links/x86_64-slc6-gcc49-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/pyanalysis/1.5_python2.7/x86_64-slc6-gcc49-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/pytools/1.9_python2.7/x86_64-slc6-gcc49-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/COOL/3_1_0/x86_64-slc6-gcc49-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/MCGenerators/lhapdf/6.1.5/x86_64-slc6-gcc49-opt/bin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/valgrind/3.11.0/x86_64-slc6-gcc49-opt/bin:/usr/lib64/qt-3.3/bin:/usr/kerberos/bin:/usr/local/bin:/bin:/usr/bin:/usr/sbin:/sbin:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/CMT/v1r25p20160527/${CMTBIN}
CLASSPATH=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/CMT/v1r25p20160527/java
debug_option=-g
cc=$(cc_name)
cdebugflags=$(coptimized_s)
cflags=-fPIC -std=c11 -fmessage-length=0 -fPIC  -g  -std=c11 
pp_cflags= $(CppSpecificFlags) $(CppSpecificFlags)
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clinkflags=-fPIC
clink=$(cc) $(clinkflags) $(cdebugflags)
cdepflags=-MMD -MP -MF $*.d -MQ $@
vsCONFIG=Release
vsOptimize=2
ppcmd=-I
preproc=c++ -MD -c 
cpp=$(cpp_name)
cppdebugflags=$(cppoptimized_s)
cppflags= -D_GNU_SOURCE -pthread -pipe -ansi -fPIC -W -Wall -pedantic -Wno-long-long  -std=c++11 -Wno-deprecated -Wno-unused-local-typedefs -g  -pedantic -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -Wno-long-long  -fno-var-tracking-assignments  -Wextra -Werror=return-type  -std=c++11  -std=c++14  $(CheckerGccPlugins_args) 
pp_cppflags=-D_GNU_SOURCE -DGAUDI_V20_COMPAT  -DBOOST_FILESYSTEM_VERSION=3  -DBOOST_SPIRIT_USE_PHOENIX_V3  -DATLAS_GAUDI_V21  -DNDEBUG  $(CppSpecificFlags) -DXAOD_MANACORE -DXAOD_ANALYSIS  $(CppSpecificFlags)
cppcomp=$(cpp) -c $(cppdebugflags) $(cppflags) $(pp_cppflags) $(includes)
cpplinkflags=-Wl,-Bdynamic $(linkdebugflags) -ldl -Wl,--as-needed -Wl,--no-undefined  -Wl,--export-dynamic  -Wl,--allow-shlib-undefined  -Wl,--hash-style=both 
cpplink=$(cpp) $(cpplinkflags)
cppdepflags=-MMD -MP -MF $*.d -MQ $@
for=$(for_name)
fflags=-fmessage-length=0 -O2 -fdollar-ok -w -fPIC -g 
fcomp=$(for) -c $(fincludes) $(fdebugflags) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=$(cpp_name) $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=$(ExternalPolicy_root)/scripts/symlink.sh
symunlink=/bin/rm -f 
library_install_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.$(tag).history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=python ${CMTROOT}/mgr/cmt_svn_checkout.py 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
GUID_all={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC955}
package_GUID={8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}
install_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo --log=./install.$(tag).history 
uninstall_command=python $(GaudiPolicy_root)/scripts/install.py -u --log=./install.$(tag).history 
cmt_installarea_command=python $(GaudiPolicy_root)/scripts/install.py -xCVS -x*~ -x*.stamp -x*.bak -x.* -x*.pyc -x*.pyo -s --log=./install.$(tag).history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(symlink_command)
cmt_uninstall_area_command=$(uninstall_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^s/][^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-sl65-gcc493
PhysicsAnpRPC_tag=$(tag)
PHYSICSANPRPCROOT=/home/hengli/testarea/RPCPerf/PhysicsNtuple/PhysicsAnpRPC
PhysicsAnpRPC_root=/home/hengli/testarea/RPCPerf/PhysicsNtuple/PhysicsAnpRPC
PHYSICSANPRPCVERSION=PhysicsAnpRPC-v1
PhysicsAnpRPC_cmtpath=/hepustc/home/hengli/testarea/RPCPerf
PhysicsAnpRPC_offset=PhysicsNtuple
PhysicsAnpRPC_project=testarea
PhysicsAnpRPC_project_release=RPCPerf
AtlasPolicy_tag=$(tag)
ATLASPOLICYROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/AtlasPolicy
AtlasPolicy_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/AtlasPolicy
ATLASPOLICYVERSION=AtlasPolicy-01-08-46-04
AtlasPolicy_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
AtlasPolicy_project=AthAnalysisBase
AtlasPolicy_project_release=2.4.30
ExternalPolicy_tag=$(tag)
EXTERNALPOLICYROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/ExternalPolicy
ExternalPolicy_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/ExternalPolicy
EXTERNALPOLICYVERSION=ExternalPolicy-00-01-72
ExternalPolicy_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
ExternalPolicy_offset=External
ExternalPolicy_project=AthAnalysisBase
ExternalPolicy_project_release=2.4.30
isProject=${CMTPROJECTPATH}notProject
PlatformPolicy_tag=$(tag)
PLATFORMPOLICYROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/PlatformPolicy
PlatformPolicy_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/PlatformPolicy
PLATFORMPOLICYVERSION=PlatformPolicy-00-00-20
PlatformPolicy_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
PlatformPolicy_offset=External
PlatformPolicy_project=AthAnalysisBase
PlatformPolicy_project_release=2.4.30
GaudiPolicy_tag=$(tag)
GAUDIPOLICYROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/GaudiPolicy
GaudiPolicy_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/GaudiPolicy
GAUDIPOLICYVERSION=GaudiPolicy-15-05-00
GaudiPolicy_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e
GaudiPolicy_project=GAUDI
GaudiPolicy_project_release=v26r2p1-lcg81e
LCG_Settings_tag=$(tag)
LCG_SETTINGSROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Settings
LCG_Settings_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Settings
LCG_SETTINGSVERSION=v1
LCG_Settings_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e
LCG_Settings_project=LCGCMT
LCG_Settings_project_release=LCGCMT_81e
LCG_releases=${SITEROOT}/sw/lcg/releases/LCG_81e
LCG_external=${SITEROOT}/sw/lcg/releases/LCG_81e
unixdirname=lib64
gcc_config_version=4.9.3
gcc_native_version=$(gcc_config_version)
gcc_home=`which gcc |sed s=/bin/gcc==g`
clang_config_version=2.8
clang_native_version=$(clang_config_version)
clang_home=$(LCG_base)/llvm/$(clang_native_version)/$(LCG_hostos)
icc_config_version=11.1/072
icc_native_version=$(icc_config_version)
cc_name=lcg-gcc-$(gcc_config_version)
cpp_name=lcg-g++-$(gcc_config_version)
cpplinkname=$(cpp_name)
for_name=lcg-gfortran-$(gcc_config_version)
COMPILER_PATH=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AtlasSite/gcc-links/x86_64-slc6-gcc49-opt/lib/gcc/x86_64-unknown-linux-gnu/4.9.3
LD_LIBRARY_PATH=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/${CMTCONFIG}/lib:/hepustc/home/hengli/testarea/RPCPerf/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/InstallArea/${CMTCONFIG}/lib:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AtlasSite/gcc-links/x86_64-slc6-gcc49-opt/lib64:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/fftw3/3.1.2/x86_64-slc6-gcc49-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/valgrind/3.11.0/x86_64-slc6-gcc49-opt/lib/valgrind:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/external/yampl/1.0/x86_64-slc6-gcc49-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/lib:/usr/lib64
Python_tag=$(tag)
PYTHONROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/Python
Python_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/Python
PYTHONVERSION=v1
Python_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e
Python_offset=LCG_Interfaces
Python_project=LCGCMT
Python_project_release=LCGCMT_81e
LCG_Configuration_tag=$(tag)
LCG_CONFIGURATIONROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Configuration
LCG_Configuration_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Configuration
LCG_CONFIGURATIONVERSION=v1
LCG_Configuration_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e
LCG_Configuration_project=LCGCMT
LCG_Configuration_project_release=LCGCMT_81e
LCG_Platforms_tag=$(tag)
LCG_PLATFORMSROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Platforms
LCG_Platforms_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Platforms
LCG_PLATFORMSVERSION=v1
LCG_Platforms_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e
LCG_Platforms_project=LCGCMT
LCG_Platforms_project_release=LCGCMT_81e
LCG_arch=x86_64
LCG_os=slc6
LCG_compiler=gcc49
LCG_mode=opt
LCG_basesystem=$(LCG_arch)-$(LCG_os)-$(LCG_compiler)
LCG_system=$(LCG_basesystem)-$(LCG_mode)
LCG_platform=$(LCG_basesystem)-$(LCG_mode)
ATLAS_TAGS_MAP=none
host_compiler=gcc44
host_arch=x86_64
host_os=slc6
host_cmtconfig=x86_64-slc6-gcc44-opt
LCG_hostos=$(host_arch)-$(host_os)
LCG_hostarch=$(host_arch)
LCG_config_version=81e
uuid_config_version=dummy
4suite_config_version=1.0.2p1
AIDA_config_version=3.2.1
Boost_config_version=1.59.0
Boost_file_version=1_59
CASTOR_config_version=2.1.13-6
CLHEP_config_version=2.2.0.4
COOL_config_version=3_1_0
CORAL_config_version=3_1_0
CppUnit_config_version=1.12.1_p1
Davix_config_version=0.4.0
Expat_config_version=2.0.1
FTS3_config_version=0.0.1-88
FTS_config_version=2.2.8emi2
Frontier_Client_config_version=2.8.18
GCCXML_config_version=0.9.0_20131026
GSL_config_version=1.10
HepMC_config_version=2.06.09
HepPDT_config_version=2.06.01
Jinja2_config_version=2.7.3
LCGCMT_config_version=LCGCMT_81b
MarkupSafe_config_version=0.23
PyYAML_config_version=3.11
Python_config_version=2.7.9.p1
Python_config_version_twodigit=2.7
QMtest_config_version=2.4.1
Qt5_config_version=5.4.1
Qt_config_version=4.8.4
RELAX_config_version=RELAX-root6
ROOT_config_version=6.04.16
WMS_config_version=3.4.0
XercesC_config_version=3.1.1p1
astroid_config_version=1.3.6
backports_config_version=3.4.0.2
blas_config_version=20110419
certifi_config_version=14.05.14
cmaketools_config_version=1.1
cmt_config_version=v1r20p20090520
coin3d_config_version=3.1.3p2
coverage_config_version=3.5.2
cream_config_version=1.14.0-4
cx_oracle_config_version=5.1.1
dcap_config_version=2.47.7-1
dm-util_config_version=1.15.0-0
doxygen_config_version=1.8.9.1
dpm_config_version=1.8.5-1
eigen_config_version=3.2.7
epel_config_version=20130408
fastjet_config_version=3.2.0
fftw_config_version=3.1.2
genshi_config_version=0.6
gfal2_config_version=2.2.0-1
gfal_config_version=1.13.0-0
gmp_config_version=6.0.0
graphviz_config_version=2.28.0
gridftp_ifce_config_version=2.3.1-0
gridsite_config_version=1.7.25-1.emi2
gtest_config_version=1.7.0
igprof_config_version=5.9.11
ipython_config_version=3.1.0
is_ifce_config_version=1.15.0-0
jemalloc_config_version=3.6.0
json_config_version=2.5.2
jsonschema_config_version=2.4.0
lapack_config_version=3.5.0
lb_config_version=3.2.9
lcgdmcommon_config_version=1.8.5-1
lcgenv_config_version=0.2
lcginfosites_config_version=3.1.0-3
lcov_config_version=1.9
lfc_config_version=1.8.5-1
libsvm_config_version=2.86
libtool_config_version=1.5.26
libunwind_config_version=5c2cade
logilabcommon_config_version=1.0.1
lxml_config_version=2.3
matplotlib_config_version=1.4.3
messaging_config_version=1.0
mistune_config_version=0.5.1
mock_config_version=0.8.0
mpich2_config_version=1.5
multiprocessing_config_version=2.6.2.1
mysql_config_version=5.5.27
mysql_python_config_version=1.2.3
neurobayes_config_version=3.7.0
neurobayes_expert_config_version=3.7.0
nose_config_version=1.1.2
numexpr_config_version=2.4.3
numpy_config_version=1.9.2
oracle_config_version=11.2.0.3.0
pacparser_config_version=1.3.1
pandas_config_version=0.16.1
pcre_config_version=8.34
pip_config_version=7.1.2
prettytable_config_version=0.7.2
processing_config_version=0.52
ptyprocess_config_version=0.4
py2neo_config_version=1.4.6
py_config_version=1.4.8
pyanalysis_config_version=1.5
pydot_config_version=1.0.28
pygments_config_version=2.0.2
pygraphics_config_version=1.5
pygsi_config_version=0.5
pyminuit_config_version=0.0.1
pyparsing_config_version=2.0.3
pyqt_config_version=4.9.5
pytest_config_version=2.2.4
python_dateutil_config_version=2.4.0
pytools_config_version=1.9
pytz_config_version=2015.4
pyxml_config_version=0.8.4p1
pyzmq_config_version=14.5.0
qwt_config_version=6.0.1
scikitlearn_config_version=0.16.1
scipy_config_version=0.15.1
setuptools_config_version=0.6c11
sip_config_version=4.14
six_config_version=1.9.0
soqt_config_version=1.5.0
sqlalchemy_config_version=0.7.7
sqlite_config_version=3070900
srm_ifce_config_version=1.13.0-0
stomppy_config_version=3.1.3
storm_config_version=0.19
subprocess32_config_version=3.2.6
swig_config_version=2.0.11
sympy_config_version=0.7.6
tbb_config_version=42_20140122
tcmalloc_config_version=2.4
terminado_config_version=0.5
tornado_config_version=4.0.2
valgrind_config_version=3.11.0
vdt_config_version=0.3.6
vectorclass_config_version=1.16
voms_config_version=2.0.9-1
xapian_config_version=1.2.21
xqilla_config_version=2.2.4p1
xrootd_config_version=4.2.3
xrootd_python_config_version=0.3.0
yamlcpp_config_version=0.5.1
Python_native_version=$(Python_config_version)
Python_home=${LCG_external}/Python/$(Python_native_version)/$(LCG_system)
Python_inc=$(Python_home)/include/python$(Python_version)
Python_version=$(Python_config_version_twodigit)
Python_libversion_cmd=python -c "print ''.join('$(Python_config_version)'.split('.')[:2])"
Python_libversion=$(Python_config_version_twodigit)
Python_include=$(Python_inc)
Python_linkopts= -L$(Python_home)/lib -lpython$(Python_libversion) -lutil -lpthread 
Python_export_paths=$(Python_home)
MANPATH=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/ROOT/6.04.16/x86_64-slc6-gcc49-opt/man:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/gccxml/0.9.0_20131026/x86_64-slc6-gcc49-opt/share/man:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/tcmalloc/2.4/x86_64-slc6-gcc49-opt/share/man:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/libunwind/5c2cade/x86_64-slc6-gcc49-opt/man:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/share/man:/usr/kerberos/man:/usr/local/share/man:/usr/share/man/overrides:/usr/share/man/en:/usr/share/man:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/ROOT/6.04.16/src/root/man
ROOT_INCLUDE_PATH=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/root-include-path:/hepustc/home/hengli/testarea/RPCPerf/InstallArea/root-include-path:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/root-include-path:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/InstallArea/root-include-path:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/InstallArea/root-include-path:/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/include:/hepustc/home/hengli/testarea/RPCPerf/InstallArea/include:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/include:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/InstallArea/include:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/InstallArea/include:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/Boost/1.59.0_python2.7/x86_64-slc6-gcc49-opt/include/boost-1_59:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/xrootd/4.2.3/x86_64-slc6-gcc49-opt/include:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/tcmalloc/2.4/x86_64-slc6-gcc49-opt/include:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/libunwind/5c2cade/x86_64-slc6-gcc49-opt/include:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/include/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/HepPDT/2.06.01/x86_64-slc6-gcc49-opt/include:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/fftw3/3.1.2/x86_64-slc6-gcc49-opt/include:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/mysql/5.5.27/x86_64-slc6-gcc49-opt/include:.:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/COOL/3_1_0/x86_64-slc6-gcc49-opt/include:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/CORAL/3_1_0/x86_64-slc6-gcc49-opt/include:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/HepMC/2.06.09/x86_64-slc6-gcc49-opt/include:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/external/clhep/2.1.2.3-atl01/x86_64-slc6-gcc49-opt/include:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/AIDA/3.2.1/x86_64-slc6-gcc49-opt/src/cpp:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/fastjet/3.2.0/x86_64-slc6-gcc49-opt/include:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/x86_64-slc6-gcc49-opt/include
tcmalloc_tag=$(tag)
TCMALLOCROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/tcmalloc
tcmalloc_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/tcmalloc
TCMALLOCVERSION=v1
tcmalloc_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e
tcmalloc_offset=LCG_Interfaces
tcmalloc_project=LCGCMT
tcmalloc_project_release=LCGCMT_81e
libunwind_tag=$(tag)
LIBUNWINDROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/libunwind
libunwind_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/libunwind
LIBUNWINDVERSION=v1
libunwind_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e
libunwind_offset=LCG_Interfaces
libunwind_project=LCGCMT
libunwind_project_release=LCGCMT_81e
libunwind_native_version=$(libunwind_config_version)
libunwind_home=$(LCG_external)/libunwind/$(libunwind_native_version)/$(LCG_system)
libunwind_include=$(libunwind_home)/include
libunwind_linkopts=-L$(libunwind_home)/lib -lunwind -lunwind-x86_64
libunwind_cppflags=-I $(libunwind_home)/include
libunwind_export_paths= $(libunwind_home)/include $(libunwind_home)/lib 
tcmalloc_native_version=$(tcmalloc_config_version)
tcmalloc_home=$(LCG_external)/tcmalloc/$(tcmalloc_native_version)/$(LCG_system)
tcmalloc_include=$(tcmalloc_home)/include
copyInclude=cp -Rup 
python_bin_module_dir=$(tag)/python
cmt_actions_constituents=       doxygen post_install post_merge_rootmap post_merge_genconfdb post_build_tpcnvdb all_post_constituents checkreq PhysicsAnpRPC_NICOS_Fix_debuginfo check_install_python_modules find_packages compile compile_pkg new_analysisapp new_pkg new_alg new_analysisalg new_asgtool new_jobo new_skeleton make_skeleton checkout_pkg cppcheck 
cmt_actions_constituentsclean= cppcheckclean checkout_pkgclean make_skeletonclean new_skeletonclean new_joboclean new_asgtoolclean new_analysisalgclean new_algclean new_pkgclean new_analysisappclean compile_pkgclean compileclean find_packagesclean check_install_python_modulesclean PhysicsAnpRPC_NICOS_Fix_debuginfoclean checkreqclean all_post_constituentsclean post_build_tpcnvdbclean post_merge_genconfdbclean post_merge_rootmapclean post_installclean doxygenclean new_rootsysclean TestProjectclean TestPackageclean qmtest_summarizeclean qmtest_runclean makeclean 
remove_command=$(cmt_uninstallarea_command)
dq="
BINDIR=$(tag)
vsDebug=2
merge_componentslist_cmd=python $(AtlasCommonPolicy_root)/scripts/merge_files.py
merge_rootmap_cmd=python $(AtlasCommonPolicy_root)/scripts/merge_files.py
libdirname=lib
bindirname=bin
lib_no_static_fragment=library_no_static
cppdebugflags_s=-Og -g
cppoptimized_s=-O2 -DNDEBUG
cppprofiled_s=-pg
cdebugflags_s=-Og -g
coptimized_s=-O2 -DNDEBUG
fdebugflags= $(foptimized_s)
fdebugflags_s=-Og -g
foptimized_s=-O2 -DNDEBUG
fprofiled_s=-pg
makeLinkMap=-Wl,-Map,Linux.map
componentshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined -pthread  -Wl,-z,max-page-size=0x1000  -Wl,--hash-style=both 
libraryshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined -pthread  -Wl,-z,max-page-size=0x1000  -Wl,--hash-style=both 
application_linkopts=-Wl,--export-dynamic 
genconfDir=$(shared_install_subdir)/genConf/
merge_genconfDb_cmd=python $(AtlasCommonPolicy_root)/scripts/merge_files.py
genconfig_configurableModuleName=GaudiKernel.Proxy
genconfig_configurableDefaultName=Configurable.DefaultName
genconfig_configurableAlgorithm=ConfigurableAlgorithm
genconfig_configurableAlgTool=ConfigurableAlgTool
genconfig_configurableAuditor=ConfigurableAuditor
genconfig_configurableService=ConfigurableService
use_GaudiCoreSvc=GaudiCoreSvc * -no_auto_imports
strip_script=$(GAUDIPOLICYROOT)/scripts/StripPath
GenConfUser_script=genconfuser.py
Reflex_tag=$(tag)
REFLEXROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/Reflex
Reflex_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/Reflex
REFLEXVERSION=v1
Reflex_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e
Reflex_offset=LCG_Interfaces
Reflex_project=LCGCMT
Reflex_project_release=LCGCMT_81e
ROOT_tag=$(tag)
ROOTROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/ROOT
ROOT_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/ROOT
ROOTVERSION=v1
ROOT_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e
ROOT_offset=LCG_Interfaces
ROOT_project=LCGCMT
ROOT_project_release=LCGCMT_81e
GCCXML_tag=$(tag)
GCCXMLROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/GCCXML
GCCXML_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/GCCXML
GCCXMLVERSION=v1
GCCXML_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e
GCCXML_offset=LCG_Interfaces
GCCXML_project=LCGCMT
GCCXML_project_release=LCGCMT_81e
GCCXML_native_version=$(GCCXML_config_version)
GCCXML_home=$(LCG_external)/gccxml/$(GCCXML_native_version)/$(LCG_system)
GCCXML_name=gccxml
GCCXML_export_paths=$(GCCXML_home)/bin $(GCCXML_home)/share 
xrootd_tag=$(tag)
XROOTDROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/xrootd
xrootd_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/xrootd
XROOTDVERSION=v1
xrootd_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e
xrootd_offset=LCG_Interfaces
xrootd_project=LCGCMT
xrootd_project_release=LCGCMT_81e
xrootd_native_version=$(xrootd_config_version)
xrootd_home=$(LCG_external)/xrootd/$(xrootd_native_version)/$(LCG_system)
xrootd_include=$(xrootd_home)/include
xrootd_linkopts=-L$(xrootd_home)/$(unixdirname) 
xrootd_export_paths= $(xrootd_home)/bin $(xrootd_home)/include $(xrootd_home)/$(unixdirname)   $(xrootd_home)/share
ROOT_native_version=$(ROOT_config_version)
ROOT_base=$(LCG_releases)/ROOT/$(ROOT_native_version)
ROOT_home=$(ROOT_base)/$(LCG_platform)
ROOT_linkopts= $(rootRooFitLibs) $(rootMathLibs) $(rootGenVectorLibs) $(rootBasicLibs) $(rootRFIOLibs) $(rootGraphicsLibs) $(rootTableLibs) $(rootSTLDictLibs) $(rootCintexLibs) $(rootTMVALibs) $(rootNetLibs) $(rootEGLibs) $(rootThreadLibs) $(rootTreePlayerLibs)  -lRIO
ROOT_Reflex_linkopts=-L$(ROOT_home)/lib -lCore 
ROOTSYS=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/ROOT/6.04.16/x86_64-slc6-gcc49-opt
ROOT_name=root
ROOT_header_file_filter=$(ROOT_home)/include
ROOT_header_file_stamp=$(ROOT_home)/include/Type.h
PYTHONPATH=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/python:/hepustc/home/hengli/testarea/RPCPerf/InstallArea/${CMTCONFIG}/lib/python2.7:/hepustc/home/hengli/testarea/RPCPerf/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/InstallArea/${CMTCONFIG}/lib/python2.7:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/InstallArea/python:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/ROOT/6.04.16/x86_64-slc6-gcc49-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/pyanalysis/1.5_python2.7/x86_64-slc6-gcc49-opt/lib/python2.7/site-packages:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/pytools/1.9_python2.7/x86_64-slc6-gcc49-opt/lib/python2.7/site-packages:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/COOL/3_1_0/x86_64-slc6-gcc49-opt/python:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/CORAL/3_1_0/x86_64-slc6-gcc49-opt/python:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/CORAL/3_1_0/x86_64-slc6-gcc49-opt/lib:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/MCGenerators/lhapdf/6.1.5/x86_64-slc6-gcc49-opt/lib/python2.7/site-packages
rootcint=rootcint
genmap_cmd=$(ROOTSYS)/bin/genmap
ROOT_export_paths= $(ROOT_home) 
Reflex_linkopts=$(ROOT_Reflex_linkopts)
genreflex_cmd=$(ROOT_home)/bin/genreflex
gccxmloptsval=--gccxml-compiler $(cpp_name) 
gccxmlopts=--gccxmlopt='$(gccxmloptsval)'
COOLVERS=3_1_0
CORALVERS=3_1_0
ROOTVERS=6.04.16
BoostVERS=1.59.0
uuidVERS=dummy
GCCXMLVERS=0.9.0_20131026
AIDAVERS=3.2.1
XercesCVERS=3.1.1p1
GSLVERS=1.10
PythonVERS=2.7.9.p1
HepMCVERS=2.06.09
QMtestVERS=2.4.1
LCGCMTVERS=81e
GAUDI_DOXY_HOME=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/GaudiRelease/doc
AtlasCommonPolicy_tag=$(tag)
ATLASCOMMONPOLICYROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/AtlasCommonPolicy
AtlasCommonPolicy_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/AtlasCommonPolicy
ATLASCOMMONPOLICYVERSION=AtlasCommonPolicy-00-00-56-01
AtlasCommonPolicy_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
AtlasCommonPolicy_project=AthAnalysisBase
AtlasCommonPolicy_project_release=2.4.30
AtlasDoxygen_tag=$(tag)
ATLASDOXYGENROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/Tools/AtlasDoxygen
AtlasDoxygen_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/Tools/AtlasDoxygen
ATLASDOXYGENVERSION=AtlasDoxygen-00-04-10
AtlasDoxygen_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
AtlasDoxygen_offset=Tools
AtlasDoxygen_project=AthAnalysisBase
AtlasDoxygen_project_release=2.4.30
library_fragment=library
SEPARATEDEBUG=1
debuginfosuffix=.debug
NICOS=NICOS${NICOS_PROJECT_RELNAME}
NICOS_TMP_A=NICOS$(NICOS_PROJECT_HOME)
NICOS_TMP_B=NICOS$(NICOS_COPY_HOME)
NICOS_TMP_C=NICOS$(NICOS_PROJECT_RELNAME_COPY)
as_needed_macro=asNeeded
Mac105_Compat_tag=$(tag)
MAC105_COMPATROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/Mac105_Compat
Mac105_Compat_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/Mac105_Compat
MAC105_COMPATVERSION=Mac105_Compat-00-00-01
Mac105_Compat_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
Mac105_Compat_offset=External
Mac105_Compat_project=AthAnalysisBase
Mac105_Compat_project_release=2.4.30
AtlasExternalArea_tag=$(tag)
ATLASEXTERNALAREAROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/AtlasExternalArea
AtlasExternalArea_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/AtlasExternalArea
ATLASEXTERNALAREAVERSION=AtlasExternalArea-00-00-27
AtlasExternalArea_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
AtlasExternalArea_offset=External
AtlasExternalArea_project=AthAnalysisBase
AtlasExternalArea_project_release=2.4.30
ATLAS_EXTERNAL=${SITEROOT}/external
LCG_ROOT=${SITEROOT}/sw/lcg
LCG_EXTERNAL=${LCG_ROOT}/external
LCG_app_system=$(LCG_platform)
LCG_ext_system=$(LCG_system)
COMMON_PACKAGES=${SITEROOT}/packages
Mac105_Compat_native_version=1.0.0
Mac105_Compat_platform=NotSupported
Mac105_Compat_base=$(ATLAS_EXTERNAL)/mac105compat/$(Mac105_Compat_native_version)
Mac105_Compat_home=$(Mac105_Compat_base)/$(Mac105_Compat_platform)
Mac105_Compat_home_install=$(Mac105_Compat_root)/$(CMTCONFIG)
Mac105_Compat_install_cmd=$(library_install_command) $(Mac105_Compat_home) $(Mac105_Compat_home_install)
libprefix=lib
ExternalPolicy_scripts= -s=$(EXTERNALPOLICYROOT)/share -s=$(EXTERNALPOLICYROOT)/src symlink.sh inverse_symlink.sh 
symlink_command=$(ExternalPolicy_root)/src/symlink.sh
symlinknew=$(symlink_command)
copy_command=cp -R -H
atlas_install_command=cp -R -H
base_URL=http://atlas.web.cern.ch/Atlas/GROUPS/SOFTWARE/OO/dist/
kits_dir=cmt/kits
zip_command=tar
AtlasCxxPolicy_tag=$(tag)
ATLASCXXPOLICYROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/AtlasCxxPolicy
AtlasCxxPolicy_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/AtlasCxxPolicy
ATLASCXXPOLICYVERSION=AtlasCxxPolicy-00-00-77
AtlasCxxPolicy_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
AtlasCxxPolicy_project=AthAnalysisBase
AtlasCxxPolicy_project_release=2.4.30
AtlasCompilers_tag=$(tag)
ATLASCOMPILERSROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/AtlasCompilers
AtlasCompilers_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/AtlasCompilers
ATLASCOMPILERSVERSION=AtlasCompilers-00-00-25
AtlasCompilers_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
AtlasCompilers_offset=External
AtlasCompilers_project=AthAnalysisBase
AtlasCompilers_project_release=2.4.30
compiler_versions=gcc=$(gcc_config_version):icc=$(icc_config_version):llvm=$(clang_config_version)
cmt_installarea_linkopts= -L/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/$(CMTUSERCONTEXT_installarea_prefix)/$(CMTCONFIG)/lib  -L/hepustc/home/hengli/testarea/RPCPerf/$(testarea_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/$(AthAnalysisBase_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/$(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib  -L/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/$(LCGCMT_installarea_prefix)/$(CMTCONFIG)/lib 
use_CheckerGccPlugins_if=CheckerGccPlugins CheckerGccPlugins-* External
CheckerGccPlugins_tag=$(tag)
CHECKERGCCPLUGINSROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/CheckerGccPlugins
CheckerGccPlugins_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/CheckerGccPlugins
CHECKERGCCPLUGINSVERSION=CheckerGccPlugins-00-01-85
CheckerGccPlugins_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
CheckerGccPlugins_offset=External
CheckerGccPlugins_project=AthAnalysisBase
CheckerGccPlugins_project_release=2.4.30
CheckerGccPlugins_native_version=CheckerGccPlugins-00-01-84
CheckerGccPlugins_home=${ATLAS_EXTERNAL}/CheckerGccPlugins/$(CheckerGccPlugins_native_version)
CheckerGccPlugins_plugin_dir=$(CheckerGccPlugins_cmtpath)/$(cmt_installarea_prefix)/$(CMTCONFIG)/lib
CheckerGccPlugins_args= -fplugin=$(CheckerGccPlugins_plugin_dir)/libchecker_gccplugins.so $(CheckerGccPlugins_enablenaming) 
AtlasCxxPolicy_pp_cppflags= -DHAVE_PRETTY_FUNCTION -DHAVE_LONG_LONG -DHAVE_BOOL -DHAVE_EXPLICIT -DHAVE_MUTABLE -DHAVE_SIGNED -DHAVE_TYPENAME -DHAVE_NEW_STYLE_CASTS -DHAVE_DYNAMIC_CAST -DHAVE_TYPEID -DHAVE_ANSI_TEMPLATE_INSTANTIATION -DHAVE_TEMPLATE_DEFAULT_ARGS -DHAVE_BROKEN_TEMPLATE_RESCOPE -DHAVE_TEMPLATE_NULL_ARGS -DHAVE_TEMPLATE_NULL_SPEC -DHAVE_TEMPLATE_PARTIAL_SPEC -DHAVE_MEMBER_TEMPLATES -DHAVE_ANSI_OPERATOR_ARROW -DHAVE_NAMESPACES -DHAVE_NAMESPACE_STD -DHAVE_NEW_IOSTREAMS -DHAVE_OSTREAM_CHAR_OVERLOAD -DHAVE_ITERATOR_TRAITS -DHAVE_ITERATOR -DHAVE_REVERSE_ITERATOR_STYLE -DHAVE_CXX_STDC_HEADERS -DHAVE_64_BITS -D__IDENTIFIER_64BIT__  -D_GLIBCXX_PERMIT_BACKWARD_HASH  '-DPACKAGE_VERSION=$(q2)$(version)$(q2)' -DPACKAGE_VERSION_UQ=$(version)  -DNDEBUG $(pp_cppflags)
q2="
CodeCheck_tag=$(tag)
CODECHECKROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/Tools/CodeCheck
CodeCheck_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/Tools/CodeCheck
CODECHECKVERSION=CodeCheck-01-02-03
CodeCheck_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
CodeCheck_offset=Tools
CodeCheck_project=AthAnalysisBase
CodeCheck_project_release=2.4.30
asNeeded_linkopt=-Wl,--as-needed
notAsNeeded_linkopt=-Wl,--no-as-needed
rootver_dependent_setup=root6_setup
abuild_gen_tpcnv_cmd=true
MAKEFLAGS= --no-print-directory  -l 
genCLIDDB_cmd=${AtlasPolicy_root}/cmt/fragments/gencliddb.py
use_CLIDComps=CLIDComps * Control -no_auto_imports
remote_launcher=ssh -f 
dependencies_fragment=dependencies
install_include_filter=*.h
AtlasPolicy_scripts= -s=../share checkreq.py 
AtlasROOT_tag=$(tag)
ATLASROOTROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/AtlasROOT
AtlasROOT_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/AtlasROOT
ATLASROOTVERSION=AtlasROOT-02-03-28
AtlasROOT_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
AtlasROOT_offset=External
AtlasROOT_project=AthAnalysisBase
AtlasROOT_project_release=2.4.30
_rootBasicLibs=-L$(ROOT_home)/lib -lCore -lTree -lpthread -lMathCore -lHist
rootBasicLibs=$(_rootBasicLibs)
rootMathLibs=-L$(ROOT_home)/lib  -lMathMore -lMinuit -lMinuit2 -lMatrix -lPhysics -lHistPainter -lHist -lRint
rootGraphicsLibs=-L$(ROOT_home)/lib -lGraf -lGraf3d -lGpad -lHtml -lPostscript -lGui -lGX11TTF -lGX11
PhysicsAnpRPC_installed_dependencies= PhysicsAnpRPC
PhysicsAnpRPC_library_dependencies= PhysicsAnpRPC PhysicsAnpRPC_optdebug_library 
PhysicsAnpRPC_installed_shlibflags= -lPhysicsAnpRPC 
PhysicsAnpRPC_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(PhysicsAnpRPC_use_linkopts) $(PhysicsAnpRPC_extra_shlibflags)
PhysicsAnpRPC_use_linkopts=    $(AtlasBoost_linkopts)  $(AtlasPolicy_linkopts)  $(AtlasCxxPolicy_linkopts)  $(CheckerGccPlugins_linkopts)  $(AtlasReflex_linkopts)  $(AtlasROOT_linkopts)  $(AtlasPython_linkopts)  $(ExternalPolicy_linkopts)  $(Mac105_Compat_linkopts)  $(AtlasExternalArea_linkopts)  $(PlatformPolicy_linkopts)  $(GaudiPolicy_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(xrootd_linkopts)  $(AtlasCommonPolicy_linkopts)  $(AtlasDoxygen_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(AtlasCompilers_linkopts)  $(LCG_Platforms_linkopts)  $(CodeCheck_linkopts) 
PhysicsAnpRPC_linkopts= -lPhysicsAnpRPC  
apply_optdebug_library=with_optdebug_library
PhysicsAnpRPC_optdebug_library_dependencies= PhysicsAnpRPC
PhysicsAnpRPC_python_modules= -s=../python *.py 
install_python_modules_dependencies=check_install_python_modules
PhysicsAnpRPC_python_init_dependencies= install_python_modules 
AtlasBoost_tag=$(tag)
ATLASBOOSTROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/AtlasBoost
AtlasBoost_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/AtlasBoost
ATLASBOOSTVERSION=AtlasBoost-00-00-11
AtlasBoost_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
AtlasBoost_offset=External
AtlasBoost_project=AthAnalysisBase
AtlasBoost_project_release=2.4.30
Boost_tag=$(tag)
BOOSTROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/Boost
Boost_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/Boost
BOOSTVERSION=v1
Boost_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e
Boost_offset=LCG_Interfaces
Boost_project=LCGCMT
Boost_project_release=LCGCMT_81e
Boost_native_version=$(Boost_config_version)_python$(Python_config_version_twodigit)
Boost_home=$(LCG_external)/Boost/$(Boost_native_version)/$(LCG_system)
Boost_include=$(Boost_home)/include/boost-$(Boost_file_version)
Boost_compiler_version=$(LCG_compiler)
Boost_linkopts=-L$(Boost_home)/lib  $(Boost_linkopts_system) $(Boost_linkopts_filesystem) $(Boost_linkopts_thread) 
Boost_linkopts_python= -lboost_python-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_system= -lboost_system-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_filesystem= -lboost_filesystem-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_filesystem_mt= -lboost_filesystem-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_iostreams= -lboost_iostreams-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_regex= -lboost_regex-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_thread= -lboost_thread-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_program_options= -lboost_program_options-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_serialization= -lboost_serialization-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_date_time= -lboost_date_time-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_linkopts_graph= -lboost_graph-$(Boost_compiler_version)-mt-$(Boost_debug)$(Boost_file_version) 
Boost_header_file_filter=$(Boost_home)/include/boost-$(Boost_file_version)
Boost_header_file_stamp=$(Boost_home)/include/boost-$(Boost_file_version)/boost/any.hpp
Boost_export_paths=$(Boost_home)
AtlasBoost_include_dirs=$(AtlasBoost_cmtpath)/$(AthAnalysisBase_installarea_prefix)/include/AtlasBoost $(AtlasBoost_cmtpath)/InstallArea/include/AtlasBoost/AtlasBoost 
AtlasBoost_pp_cppflags= -I$(AtlasBoost_cmtpath)/InstallArea/include/AtlasBoost/AtlasBoost 
AtlasPython_tag=$(tag)
ATLASPYTHONROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/AtlasPython
AtlasPython_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/AtlasPython
ATLASPYTHONVERSION=AtlasPython-00-01-07
AtlasPython_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
AtlasPython_offset=External
AtlasPython_project=AthAnalysisBase
AtlasPython_project_release=2.4.30
py_distutils_ldflags=$(Python_linkopts) -shared $(cpplinkflags) $(cmt_installarea_linkopts)
py_distutils_cc=$(cc) -fno-strict-aliasing
py_distutils_cflags=$(cflags) -fno-strict-aliasing $(cppflags) $(cppdebugflags)
py_distutils_cxx=$(cpp) -fno-strict-aliasing
py_distutils_cxxflags=$(cppflags) $(cppdebugflags)
py_distutils_fcompiler=$(for)
py_distutils_fflags=$(fflags)
py_distutils_cppflags=$(includes)
AtlasReflex_tag=$(tag)
ATLASREFLEXROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/AtlasReflex
AtlasReflex_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/AtlasReflex
ATLASREFLEXVERSION=AtlasReflex-00-03-10
AtlasReflex_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
AtlasReflex_offset=External
AtlasReflex_project=AthAnalysisBase
AtlasReflex_project_release=2.4.30
AtlasRELAX_tag=$(tag)
ATLASRELAXROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/AtlasRELAX
AtlasRELAX_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/External/AtlasRELAX
ATLASRELAXVERSION=AtlasRELAX-00-01-00
AtlasRELAX_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
AtlasRELAX_offset=External
AtlasRELAX_project=AthAnalysisBase
AtlasRELAX_project_release=2.4.30
RELAX_tag=$(tag)
RELAXROOT=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/RELAX
RELAX_root=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/LCG_Interfaces/RELAX
RELAXVERSION=v1
RELAX_cmtpath=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e
RELAX_offset=LCG_Interfaces
RELAX_project=LCGCMT
RELAX_project_release=LCGCMT_81e
RELAX_native_version=$(RELAX_config_version)
RELAX_base=$(LCG_releases)/RELAX/$(RELAX_native_version)
RELAX_home=$(RELAX_base)/$(LCG_platform)
RELAX_export_paths= $(RELAX_home)/lib  
merge_dict_rootmap_cmd=${GaudiPolicy_root}/scripts/merge_files.py
genreflex_options= -Wno-deprecated  -D_GLIBCXX_PERMIT_BACKWARD_HASH 
CMTUSERCONTEXT_tag=$(tag)
CMTUSERCONTEXTROOT=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt
CMTUSERCONTEXT_root=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt
CMTUSERCONTEXTVERSION=v0
CMTUSERCONTEXT_cmtpath=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt
CMTUSERCONTEXT_project=CMTUSERCONTEXT
CMTUSERCONTEXT_project_release=cmt
GaudiPolicyDir=${GAUDIPOLICYROOT}/${BINDIR}
PlatformPolicyDir=${PLATFORMPOLICYROOT}/${BINDIR}
AtlasExternalAreaDir=${ATLASEXTERNALAREAROOT}/${BINDIR}
Mac105_CompatDir=${MAC105_COMPATROOT}/${BINDIR}
ExternalPolicyDir=${EXTERNALPOLICYROOT}/${BINDIR}
CheckerGccPluginsDir=${CHECKERGCCPLUGINSROOT}/${BINDIR}
AtlasCxxPolicyDir=${ATLASCXXPOLICYROOT}/${BINDIR}
AtlasPolicyDir=${ATLASPOLICYROOT}/${BINDIR}
AtlasROOTDir=${ATLASROOTROOT}/${BINDIR}
AtlasBoostDir=${ATLASBOOSTROOT}/${BINDIR}
AtlasPythonDir=${ATLASPYTHONROOT}/${BINDIR}
AtlasRELAXDir=${ATLASRELAXROOT}/${BINDIR}
AtlasReflexDir=${ATLASREFLEXROOT}/${BINDIR}
PhysicsAnpRPCDir=${PHYSICSANPRPCROOT}/${BINDIR}
generate_manifest_file_output=$(CMTINSTALLAREA)/$(tag)/manifest.xml
generate_manifest_file_deps=FORCE
generate_manifest_file_command=python $(GaudiPolicy_root)/scripts/project_manifest.py -o $(generate_manifest_file_output) $(PhysicsAnpRPC_cmtpath)/CMakeLists.txt $(LCG_config_version) $(tag)
generate_manifest_file_applied=NullCommand
dummy_for_NullCommand=generate_manifest_file 
need_pack_dist_check=`test -z '$(PhysicsAnpRPC_export_paths)'&&echo no_pack_dist_check||echo do_pack_dist_check`
AtlasBoost_root_include_path=$(AtlasBoost_cmtpath)/$(AthAnalysisBase_installarea_prefix)/root-include-path
PhysicsAnpRPC_include_dirs=$(PHYSICSANPRPCROOT)
PhysicsAnpRPC_root_include_path=$(PHYSICSANPRPCROOT)
tag=x86_64-slc6-gcc49-opt
package=PhysicsAnpRPC
version=PhysicsAnpRPC-v1
PACKAGE_ROOT=$(PHYSICSANPRPCROOT)
srcdir=../src
bin=../$(PhysicsAnpRPC_tag)/
javabin=../classes/
mgrdir=cmt
BIN=/home/hengli/testarea/RPCPerf/PhysicsNtuple/PhysicsAnpRPC/x86_64-slc6-gcc49-opt/
project=testarea
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(LCGCMT_installarea_prefix)/$(CMTCONFIG)/lib $(LCGCMT_installarea_prefix)/share/lib $(LCGCMT_installarea_prefix)/share/bin $(GAUDI_installarea_prefix)/$(CMTCONFIG)/lib $(GAUDI_installarea_prefix)/share/lib $(GAUDI_installarea_prefix)/share/bin $(AthAnalysisBase_installarea_prefix)/$(CMTCONFIG)/lib $(AthAnalysisBase_installarea_prefix)/share/lib $(AthAnalysisBase_installarea_prefix)/share/bin $(testarea_installarea_prefix)/$(CMTCONFIG)/lib $(testarea_installarea_prefix)/share/lib $(testarea_installarea_prefix)/share/bin $(CMTUSERCONTEXT_installarea_prefix)/$(CMTCONFIG)/lib $(CMTUSERCONTEXT_installarea_prefix)/share/lib $(CMTUSERCONTEXT_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(PhysicsAnpRPC_linkopts)  $(AtlasBoost_linkopts)  $(AtlasPolicy_linkopts)  $(AtlasCxxPolicy_linkopts)  $(CheckerGccPlugins_linkopts)  $(AtlasReflex_linkopts)  $(AtlasROOT_linkopts)  $(AtlasPython_linkopts)  $(ExternalPolicy_linkopts)  $(Mac105_Compat_linkopts)  $(AtlasExternalArea_linkopts)  $(PlatformPolicy_linkopts)  $(GaudiPolicy_linkopts)  $(ROOT_linkopts)  $(Boost_linkopts)  $(Python_linkopts)  $(xrootd_linkopts)  $(AtlasCommonPolicy_linkopts)  $(AtlasDoxygen_linkopts)  $(LCG_Settings_linkopts)  $(LCG_Configuration_linkopts)  $(AtlasCompilers_linkopts)  $(LCG_Platforms_linkopts)  $(CodeCheck_linkopts) 
LCGCMT_installarea_prefix=$(cmt_installarea_prefix)
LCGCMT_installarea_prefix_remove=$(LCGCMT_installarea_prefix)
GAUDI_installarea_prefix=$(cmt_installarea_prefix)
GAUDI_installarea_prefix_remove=$(GAUDI_installarea_prefix)
AthAnalysisBase_installarea_prefix=$(cmt_installarea_prefix)
AthAnalysisBase_installarea_prefix_remove=$(AthAnalysisBase_installarea_prefix)
testarea_installarea_prefix=$(cmt_installarea_prefix)
testarea_installarea_prefix_remove=$(testarea_installarea_prefix)
CMTUSERCONTEXT_installarea_prefix=$(cmt_installarea_prefix)
CMTUSERCONTEXT_installarea_prefix_remove=$(CMTUSERCONTEXT_installarea_prefix)
LCGCMT_home=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e
GAUDI_home=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e
AthAnalysisBase_home=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30
testarea_home=/hepustc/home/hengli/testarea/RPCPerf
CMTUSERCONTEXT_home=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt
lcgcmt_pp=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/$(LCGCMT_installarea_prefix)/$(CMTCONFIG)/lib/python$(Python_config_version_twodigit)/site-packages
CMTUSERCONTEXT_install_include=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/$(CMTUSERCONTEXT_installarea_prefix)$(shared_install_subdir)/include
testarea_install_include=/hepustc/home/hengli/testarea/RPCPerf/$(testarea_installarea_prefix)$(shared_install_subdir)/include
AthAnalysisBase_install_include=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/$(AthAnalysisBase_installarea_prefix)$(shared_install_subdir)/include
GAUDI_install_include=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/$(GAUDI_installarea_prefix)$(shared_install_subdir)/include
LCGCMT_install_include=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/$(LCGCMT_installarea_prefix)$(shared_install_subdir)/include
LCGCMT_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/$(LCGCMT_installarea_prefix)$(shared_install_subdir)/python
GAUDI_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/$(GAUDI_installarea_prefix)$(shared_install_subdir)/python
AthAnalysisBase_install_python=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/$(AthAnalysisBase_installarea_prefix)$(shared_install_subdir)/python
testarea_install_python=/hepustc/home/hengli/testarea/RPCPerf/$(testarea_installarea_prefix)$(shared_install_subdir)/python
CMTUSERCONTEXT_install_python=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/$(CMTUSERCONTEXT_installarea_prefix)$(shared_install_subdir)/python
LCGCMT_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/$(LCGCMT_installarea_prefix)/$(python_bin_module_dir)
GAUDI_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/$(GAUDI_installarea_prefix)/$(python_bin_module_dir)
AthAnalysisBase_install_pyd_module=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/$(AthAnalysisBase_installarea_prefix)/$(python_bin_module_dir)
testarea_install_pyd_module=/hepustc/home/hengli/testarea/RPCPerf/$(testarea_installarea_prefix)/$(python_bin_module_dir)
CMTUSERCONTEXT_install_pyd_module=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/$(CMTUSERCONTEXT_installarea_prefix)/$(python_bin_module_dir)
scripts_offset=.
scripts_maindir=scripts
scripts_dir=$(scripts_maindir)
LCGCMT_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/$(LCGCMT_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
GAUDI_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/$(GAUDI_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
AthAnalysisBase_install_scripts=/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/$(AthAnalysisBase_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
testarea_install_scripts=/hepustc/home/hengli/testarea/RPCPerf/$(testarea_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
CMTUSERCONTEXT_install_scripts=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/$(CMTUSERCONTEXT_installarea_prefix)$(shared_install_subdir)/$(scripts_dir)
genconfInstallDir=/hepustc/home/hengli/testarea/RPCPerf/$(testarea_installarea_prefix)$(shared_install_subdir)/python
JOBOPTSEARCHPATH=.:/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/jobOptions:/hepustc/home/hengli/testarea/RPCPerf/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/InstallArea/jobOptions:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/InstallArea/jobOptions
DATAPATH=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/${CMTCONFIG}/share:/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/share:/hepustc/home/hengli/testarea/RPCPerf/InstallArea/${CMTCONFIG}/share:/hepustc/home/hengli/testarea/RPCPerf/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/${CMTCONFIG}/share:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/InstallArea/${CMTCONFIG}/share:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/InstallArea/${CMTCONFIG}/share:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/InstallArea/share:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/PartPropSvc/share
ROOTMAPSEARCHPATH=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/rootmap:/hepustc/home/hengli/testarea/RPCPerf/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/InstallArea/rootmap:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/InstallArea/rootmap
XMLPATH=/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/XML:/hepustc/home/hengli/testarea/RPCPerf/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/InstallArea/XML:/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/InstallArea/XML
CMTINSTALLAREA=/hepustc/home/hengli/testarea/RPCPerf/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(AtlasBoost_root)/cmt/requirements $(AtlasPolicy_root)/cmt/requirements $(AtlasCxxPolicy_root)/cmt/requirements $(CheckerGccPlugins_root)/cmt/requirements $(AtlasReflex_root)/cmt/requirements $(AtlasROOT_root)/cmt/requirements $(AtlasPython_root)/cmt/requirements $(AtlasRELAX_root)/cmt/requirements $(ExternalPolicy_root)/cmt/requirements $(Mac105_Compat_root)/cmt/requirements $(AtlasExternalArea_root)/cmt/requirements $(PlatformPolicy_root)/cmt/requirements $(GaudiPolicy_root)/cmt/requirements $(Reflex_root)/cmt/requirements $(ROOT_root)/cmt/requirements $(Boost_root)/cmt/requirements $(Python_root)/cmt/requirements $(tcmalloc_root)/cmt/requirements $(libunwind_root)/cmt/requirements $(GCCXML_root)/cmt/requirements $(xrootd_root)/cmt/requirements $(AtlasCommonPolicy_root)/cmt/requirements $(AtlasDoxygen_root)/cmt/requirements $(RELAX_root)/cmt/requirements $(LCG_Settings_root)/cmt/requirements $(LCG_Configuration_root)/cmt/requirements $(AtlasCompilers_root)/cmt/requirements $(LCG_Platforms_root)/cmt/requirements $(CodeCheck_root)/cmt/requirements 
use_includes= $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/include/AtlasBoost" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/include/AtlasBoost/AtlasBoost" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/AtlasCxxPolicy" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/ROOT/6.04.16/x86_64-slc6-gcc49-opt/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/Boost/1.59.0_python2.7/x86_64-slc6-gcc49-opt/include/boost-1_59" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/Python/2.7.9.p1/x86_64-slc6-gcc49-opt/include/python2.7" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/sw/lcg/releases/LCG_81e/xrootd/4.2.3/x86_64-slc6-gcc49-opt/include" $(ppcmd)"$(AtlasCommonPolicy_root)/src" $(ppcmd)"$(AtlasCompilers_root)/src" $(ppcmd)"$(LCG_Platforms_root)/src" 
use_fincludes= $(use_includes)
use_stamps=  $(PhysicsAnpRPC_stamps)  $(AtlasBoost_stamps)  $(AtlasPolicy_stamps)  $(AtlasCxxPolicy_stamps)  $(CheckerGccPlugins_stamps)  $(AtlasReflex_stamps)  $(AtlasROOT_stamps)  $(AtlasPython_stamps)  $(ExternalPolicy_stamps)  $(Mac105_Compat_stamps)  $(AtlasExternalArea_stamps)  $(PlatformPolicy_stamps)  $(GaudiPolicy_stamps)  $(ROOT_stamps)  $(Boost_stamps)  $(Python_stamps)  $(xrootd_stamps)  $(AtlasCommonPolicy_stamps)  $(AtlasDoxygen_stamps)  $(LCG_Settings_stamps)  $(LCG_Configuration_stamps)  $(AtlasCompilers_stamps)  $(LCG_Platforms_stamps)  $(CodeCheck_stamps) 
use_cflags=  $(PhysicsAnpRPC_cflags)  $(AtlasBoost_cflags)  $(AtlasPolicy_cflags)  $(AtlasCxxPolicy_cflags)  $(CheckerGccPlugins_cflags)  $(AtlasReflex_cflags)  $(AtlasROOT_cflags)  $(AtlasPython_cflags)  $(ExternalPolicy_cflags)  $(Mac105_Compat_cflags)  $(AtlasExternalArea_cflags)  $(PlatformPolicy_cflags)  $(GaudiPolicy_cflags)  $(ROOT_cflags)  $(Boost_cflags)  $(Python_cflags)  $(xrootd_cflags)  $(AtlasCommonPolicy_cflags)  $(AtlasDoxygen_cflags)  $(LCG_Settings_cflags)  $(LCG_Configuration_cflags)  $(AtlasCompilers_cflags)  $(LCG_Platforms_cflags)  $(CodeCheck_cflags) 
use_pp_cflags=  $(PhysicsAnpRPC_pp_cflags)  $(AtlasBoost_pp_cflags)  $(AtlasPolicy_pp_cflags)  $(AtlasCxxPolicy_pp_cflags)  $(CheckerGccPlugins_pp_cflags)  $(AtlasReflex_pp_cflags)  $(AtlasROOT_pp_cflags)  $(AtlasPython_pp_cflags)  $(ExternalPolicy_pp_cflags)  $(Mac105_Compat_pp_cflags)  $(AtlasExternalArea_pp_cflags)  $(PlatformPolicy_pp_cflags)  $(GaudiPolicy_pp_cflags)  $(ROOT_pp_cflags)  $(Boost_pp_cflags)  $(Python_pp_cflags)  $(xrootd_pp_cflags)  $(AtlasCommonPolicy_pp_cflags)  $(AtlasDoxygen_pp_cflags)  $(LCG_Settings_pp_cflags)  $(LCG_Configuration_pp_cflags)  $(AtlasCompilers_pp_cflags)  $(LCG_Platforms_pp_cflags)  $(CodeCheck_pp_cflags) 
use_cppflags=  $(PhysicsAnpRPC_cppflags)  $(AtlasBoost_cppflags)  $(AtlasPolicy_cppflags)  $(AtlasCxxPolicy_cppflags)  $(CheckerGccPlugins_cppflags)  $(AtlasReflex_cppflags)  $(AtlasROOT_cppflags)  $(AtlasPython_cppflags)  $(ExternalPolicy_cppflags)  $(Mac105_Compat_cppflags)  $(AtlasExternalArea_cppflags)  $(PlatformPolicy_cppflags)  $(GaudiPolicy_cppflags)  $(ROOT_cppflags)  $(Boost_cppflags)  $(Python_cppflags)  $(xrootd_cppflags)  $(AtlasCommonPolicy_cppflags)  $(AtlasDoxygen_cppflags)  $(LCG_Settings_cppflags)  $(LCG_Configuration_cppflags)  $(AtlasCompilers_cppflags)  $(LCG_Platforms_cppflags)  $(CodeCheck_cppflags) 
use_pp_cppflags=  $(PhysicsAnpRPC_pp_cppflags)  $(AtlasBoost_pp_cppflags)  $(AtlasPolicy_pp_cppflags)  $(AtlasCxxPolicy_pp_cppflags)  $(CheckerGccPlugins_pp_cppflags)  $(AtlasReflex_pp_cppflags)  $(AtlasROOT_pp_cppflags)  $(AtlasPython_pp_cppflags)  $(ExternalPolicy_pp_cppflags)  $(Mac105_Compat_pp_cppflags)  $(AtlasExternalArea_pp_cppflags)  $(PlatformPolicy_pp_cppflags)  $(GaudiPolicy_pp_cppflags)  $(ROOT_pp_cppflags)  $(Boost_pp_cppflags)  $(Python_pp_cppflags)  $(xrootd_pp_cppflags)  $(AtlasCommonPolicy_pp_cppflags)  $(AtlasDoxygen_pp_cppflags)  $(LCG_Settings_pp_cppflags)  $(LCG_Configuration_pp_cppflags)  $(AtlasCompilers_pp_cppflags)  $(LCG_Platforms_pp_cppflags)  $(CodeCheck_pp_cppflags) 
use_fflags=  $(PhysicsAnpRPC_fflags)  $(AtlasBoost_fflags)  $(AtlasPolicy_fflags)  $(AtlasCxxPolicy_fflags)  $(CheckerGccPlugins_fflags)  $(AtlasReflex_fflags)  $(AtlasROOT_fflags)  $(AtlasPython_fflags)  $(ExternalPolicy_fflags)  $(Mac105_Compat_fflags)  $(AtlasExternalArea_fflags)  $(PlatformPolicy_fflags)  $(GaudiPolicy_fflags)  $(ROOT_fflags)  $(Boost_fflags)  $(Python_fflags)  $(xrootd_fflags)  $(AtlasCommonPolicy_fflags)  $(AtlasDoxygen_fflags)  $(LCG_Settings_fflags)  $(LCG_Configuration_fflags)  $(AtlasCompilers_fflags)  $(LCG_Platforms_fflags)  $(CodeCheck_fflags) 
use_pp_fflags=  $(PhysicsAnpRPC_pp_fflags)  $(AtlasBoost_pp_fflags)  $(AtlasPolicy_pp_fflags)  $(AtlasCxxPolicy_pp_fflags)  $(CheckerGccPlugins_pp_fflags)  $(AtlasReflex_pp_fflags)  $(AtlasROOT_pp_fflags)  $(AtlasPython_pp_fflags)  $(ExternalPolicy_pp_fflags)  $(Mac105_Compat_pp_fflags)  $(AtlasExternalArea_pp_fflags)  $(PlatformPolicy_pp_fflags)  $(GaudiPolicy_pp_fflags)  $(ROOT_pp_fflags)  $(Boost_pp_fflags)  $(Python_pp_fflags)  $(xrootd_pp_fflags)  $(AtlasCommonPolicy_pp_fflags)  $(AtlasDoxygen_pp_fflags)  $(LCG_Settings_pp_fflags)  $(LCG_Configuration_pp_fflags)  $(AtlasCompilers_pp_fflags)  $(LCG_Platforms_pp_fflags)  $(CodeCheck_pp_fflags) 
use_libraries= $(AtlasBoost_libraries)  $(AtlasPolicy_libraries)  $(AtlasCxxPolicy_libraries)  $(CheckerGccPlugins_libraries)  $(AtlasReflex_libraries)  $(AtlasROOT_libraries)  $(AtlasPython_libraries)  $(AtlasRELAX_libraries)  $(ExternalPolicy_libraries)  $(Mac105_Compat_libraries)  $(AtlasExternalArea_libraries)  $(PlatformPolicy_libraries)  $(GaudiPolicy_libraries)  $(Reflex_libraries)  $(ROOT_libraries)  $(Boost_libraries)  $(Python_libraries)  $(tcmalloc_libraries)  $(libunwind_libraries)  $(GCCXML_libraries)  $(xrootd_libraries)  $(AtlasCommonPolicy_libraries)  $(AtlasDoxygen_libraries)  $(RELAX_libraries)  $(LCG_Settings_libraries)  $(LCG_Configuration_libraries)  $(AtlasCompilers_libraries)  $(LCG_Platforms_libraries)  $(CodeCheck_libraries) 
includes= $(ppcmd)"/home/hengli/testarea/RPCPerf/PhysicsNtuple/PhysicsAnpRPC" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/tools/slc6/cmt/InstallArea/include" $(ppcmd)"/hepustc/home/hengli/testarea/RPCPerf/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/AthAnalysisBase/2.4.30/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/GAUDI/v26r2p1-lcg81e/InstallArea/include" $(ppcmd)"/cvmfs/atlas.cern.ch/repo/sw/software/AthAnalysisBase/x86_64-slc6-gcc49-opt/2.4.30/LCGCMT/LCGCMT_81e/InstallArea/include" $(use_includes)
fincludes= $(includes)
PhysicsAnpRPC_optdebug_library_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
PhysicsAnpRPC_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
install_python_modules_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
PhysicsAnpRPCrchk_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
install_root_include_path_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
install_includes_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
CompilePython_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_run_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
qmtest_summarize_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestPackage_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
TestProject_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_rootsys_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
doxygen_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
post_install_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
post_merge_rootmap_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
post_merge_genconfdb_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
post_build_tpcnvdb_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
all_post_constituents_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
checkreq_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
PhysicsAnpRPC_NICOS_Fix_debuginfo_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
check_install_python_modules_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
find_packages_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
compile_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
compile_pkg_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_analysisapp_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_pkg_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_alg_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_analysisalg_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_asgtool_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_jobo_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
new_skeleton_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_skeleton_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
checkout_pkg_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
cppcheck_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= PhysicsAnpRPC_optdebug_library PhysicsAnpRPC install_python_modules install_root_include_path install_includes 
all_constituents= $(constituents)
constituentsclean= install_includesclean install_root_include_pathclean install_python_modulesclean PhysicsAnpRPCclean PhysicsAnpRPC_optdebug_libraryclean 
all_constituentsclean= $(constituentsclean)
rulechecker_constituents= PhysicsAnpRPCrchk 
rulechecker_constituentsclean= PhysicsAnpRPCrchkclean 
